// Sample prediction data used across the dashboard and landing page.
// In production this is replaced by data from the predictionsApi.

export const todaysFreePredictions = [
  {
    id: 'f1',
    match: 'Manchester City vs Arsenal',
    league: 'Premier League',
    type: '1X2',
    prediction: '1',
    odds: '1.85',
    confidence: 84,
    isPremium: false,
    time: 'Today, 17:00',
    kickoff: 'Today, 17:00',
  },
  {
    id: 'f2',
    match: 'Bayern Munich vs Leipzig',
    league: 'Bundesliga',
    type: 'Over 2.5 Goals',
    prediction: 'Over 2.5',
    odds: '1.72',
    confidence: 86,
    isPremium: false,
    time: 'Today, 18:30',
    kickoff: 'Today, 18:30',
  },
  {
    id: 'f3',
    match: 'Liverpool vs Tottenham',
    league: 'Premier League',
    type: 'BTTS',
    prediction: 'Yes',
    odds: '1.68',
    confidence: 81,
    isPremium: false,
    time: 'Today, 20:00',
    kickoff: 'Today, 20:00',
  },
  {
    id: 'f4',
    match: 'Inter Milan vs Juventus',
    league: 'Serie A',
    type: 'Double Chance',
    prediction: '1X',
    odds: '1.40',
    confidence: 88,
    isPremium: false,
    time: 'Today, 19:45',
    kickoff: 'Today, 19:45',
  },
];

export const todaysPremiumPredictions = [
  {
    id: 'p1',
    match: 'Barcelona vs Real Madrid',
    league: 'La Liga',
    type: 'Correct Score',
    prediction: '2-1',
    odds: '8.50',
    confidence: 76,
    isPremium: true,
    time: 'Today, 21:00',
    kickoff: 'Today, 21:00',
  },
  {
    id: 'p2',
    match: 'Chelsea vs Man Utd',
    league: 'Premier League',
    type: 'Banker Tips',
    prediction: '2',
    odds: '2.30',
    confidence: 91,
    isPremium: true,
    time: 'Today, 18:00',
    kickoff: 'Today, 18:00',
  },
  {
    id: 'p3',
    match: 'PSG vs Marseille',
    league: 'Ligue 1',
    type: 'HT/FT',
    prediction: '1/1',
    odds: '3.20',
    confidence: 74,
    isPremium: true,
    time: 'Today, 21:45',
    kickoff: 'Today, 21:45',
  },
  {
    id: 'p4',
    match: 'Dortmund vs Leverkusen',
    league: 'Bundesliga',
    type: 'VIP Predictions',
    prediction: 'Over 3.5',
    odds: '2.75',
    confidence: 82,
    isPremium: true,
    time: 'Today, 20:30',
    kickoff: 'Today, 20:30',
  },
];

export const featuredMatch = {
  id: 'fm1',
  home: 'Manchester City',
  away: 'Arsenal',
  league: 'Premier League',
  kickoff: 'Today, 17:00',
  prediction: '1',
  odds: '1.85',
  confidence: 91,
  type: 'Banker Tips',
  analysis:
    'City are unbeaten in 14 home matches, with Arsenal missing two key defenders. Our models strongly favor a home win with high confidence.',
};

export const monthlyPerformance = [
  { month: 'Aug', won: 42, lost: 8 },
  { month: 'Sep', won: 38, lost: 12 },
  { month: 'Oct', won: 45, lost: 5 },
  { month: 'Nov', won: 40, lost: 10 },
  { month: 'Dec', won: 48, lost: 4 },
  { month: 'Jan', won: 44, lost: 7 },
];

export const recentWinningPredictions = [
  {
    id: 'w1',
    match: 'Man City vs Arsenal',
    league: 'Premier League',
    type: '1X2',
    prediction: '1',
    odds: '1.85',
    result: 'won',
    date: 'Today',
  },
  {
    id: 'w2',
    match: 'Liverpool vs Tottenham',
    league: 'Premier League',
    type: 'Over 2.5 Goals',
    prediction: 'Over 2.5',
    odds: '1.72',
    result: 'won',
    date: 'Today',
  },
  {
    id: 'w3',
    match: 'Bayern vs Leipzig',
    league: 'Bundesliga',
    type: 'BTTS',
    prediction: 'Yes',
    odds: '1.68',
    result: 'won',
    date: 'Yesterday',
  },
  {
    id: 'w4',
    match: 'Chelsea vs Man Utd',
    league: 'Premier League',
    type: 'Double Chance',
    prediction: '1X',
    odds: '1.40',
    result: 'won',
    date: 'Yesterday',
  },
  {
    id: 'w5',
    match: 'Inter vs Juventus',
    league: 'Serie A',
    type: 'Correct Score',
    prediction: '2-0',
    odds: '7.20',
    result: 'won',
    date: '2 days ago',
  },
];

export const predictionAccuracyByCategory = [
  { label: '1X2', value: 91, color: '#00E5FF' },
  { label: 'Over/Under', value: 86, color: '#7C4DFF' },
  { label: 'BTTS', value: 84, color: '#00E676' },
  { label: 'Correct Score', value: 74, color: '#FFD700' },
  { label: 'HT/FT', value: 68, color: '#FF9100' },
  { label: 'Banker Tips', value: 93, color: '#00B8CC' },
];

export const platformStats = [
  { value: '87%', label: 'Win Rate', icon: '🏆' },
  { value: '50+', label: 'Daily Picks', icon: '📊' },
  { value: '19', label: 'Categories', icon: '🎯' },
  { value: '10K+', label: 'Happy Bettors', icon: '👥' },
];
